name: Deploy Phaser3 App

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  deploy-parcel-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Install dependencies
        run: yarn install

      - name: Rebuild the docs/ directory
        run: npm run build
          
      - name: Copy files to root
        run: |
          cp -r ./dist/* .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
        run: |
          mkdir -p /home/runner/actions_github_pages_1696542870182
          cp -r /home/runner/work/phaser-spacegame/phaser-spacegame/dist/* /home/runner/actions_github_pages_1696542870182/